apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-service
spec:
  selector:
    app: {{ .Values.appname }}
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: {{ .Values.appport }}
  type: LoadBalancer
