  apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "whereami-grpc"
  spec:
    ports:
    - port: 9090
      protocol: TCP
      name: grpc # adding for Istio
    selector:
      app: "whereami-grpc"
    type: "LoadBalancer"