apiVersion: v1
kind: ConfigMap
metadata:
  name: whereami-grpc-configmap
data:
  BACKEND_ENABLED: "False"
  # when defining the BACKEND_SERVICE using an HTTP protocol, indicate HTTP or HTTPS; if using gRPC, use the host name only
  BACKEND_SERVICE: "whereami-grpc-backend" # substitute with corresponding service name - this example assumes both services are in the same namespace  
  METADATA: "grpc-backend"
  GRPC_ENABLED: "True"